# Generated by Django 3.2.21 on 2023-10-19 08:16

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='caption',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='gallery-image'),
        ),
    ]
