# Generated by Django 3.2.21 on 2023-10-24 17:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20231019_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='header-image'),
        ),
    ]
